services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Plenta\NewsLikeBundle\:
        resource: ../src
        exclude: ../src/{Entity,Migrations,Model,Resources,Tests,Widget}
